-- Divine Circle: permisos del equipo, registro de actividad y limite de pedidos web. Una sentencia por linea. Pegar todo y Run, despues de precios.sql.
-- Dueno y admin: todo. Equipo (staff): ve todo, anota y edita ventas, pedidos, clientes y fijos; anota salidas; no cambia catalogo, precios, proyectos ni facturas; no borra (salvo ventas sin cobrar ni facturar, y una salida recien anotada).
drop policy if exists "projects: equipo gestiona" on public.projects;
drop policy if exists "projects: admins gestionan" on public.projects;
create policy "projects: admins gestionan" on public.projects for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "offerings: equipo gestiona" on public.offerings;
drop policy if exists "offerings: admins gestionan" on public.offerings;
create policy "offerings: admins gestionan" on public.offerings for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "orders: solo equipo" on public.orders;
drop policy if exists "orders: equipo ve" on public.orders;
drop policy if exists "orders: equipo anota" on public.orders;
drop policy if exists "orders: equipo edita" on public.orders;
drop policy if exists "orders: borrar" on public.orders;
create policy "orders: equipo ve" on public.orders for select using (public.is_member());
create policy "orders: equipo anota" on public.orders for insert with check (public.is_member());
create policy "orders: equipo edita" on public.orders for update using (public.is_member()) with check (public.is_member());
create policy "orders: borrar" on public.orders for delete using (public.is_admin() or (public.is_member() and pay <> 'paid' and invoice_id is null));
drop policy if exists "clients: solo equipo" on public.clients;
drop policy if exists "clients: equipo ve" on public.clients;
drop policy if exists "clients: equipo anota" on public.clients;
drop policy if exists "clients: equipo edita" on public.clients;
drop policy if exists "clients: admins borran" on public.clients;
create policy "clients: equipo ve" on public.clients for select using (public.is_member());
create policy "clients: equipo anota" on public.clients for insert with check (public.is_member());
create policy "clients: equipo edita" on public.clients for update using (public.is_member()) with check (public.is_member());
create policy "clients: admins borran" on public.clients for delete using (public.is_admin());
drop policy if exists "invoices: solo equipo" on public.invoices;
drop policy if exists "invoices: equipo ve" on public.invoices;
drop policy if exists "invoices: admins gestionan" on public.invoices;
create policy "invoices: equipo ve" on public.invoices for select using (public.is_member());
create policy "invoices: admins gestionan" on public.invoices for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "expenses: solo equipo" on public.expenses;
drop policy if exists "expenses: equipo ve" on public.expenses;
drop policy if exists "expenses: equipo anota" on public.expenses;
drop policy if exists "expenses: admins editan" on public.expenses;
drop policy if exists "expenses: borrar" on public.expenses;
create policy "expenses: equipo ve" on public.expenses for select using (public.is_member());
create policy "expenses: equipo anota" on public.expenses for insert with check (public.is_member());
create policy "expenses: admins editan" on public.expenses for update using (public.is_admin()) with check (public.is_admin());
create policy "expenses: borrar" on public.expenses for delete using (public.is_admin() or (public.is_member() and created_at > now() - interval '15 minutes'));
drop policy if exists "recurring: solo equipo" on public.recurring;
drop policy if exists "recurring: equipo ve" on public.recurring;
drop policy if exists "recurring: equipo anota" on public.recurring;
drop policy if exists "recurring: equipo edita" on public.recurring;
drop policy if exists "recurring: admins borran" on public.recurring;
create policy "recurring: equipo ve" on public.recurring for select using (public.is_member());
create policy "recurring: equipo anota" on public.recurring for insert with check (public.is_member());
create policy "recurring: equipo edita" on public.recurring for update using (public.is_member()) with check (public.is_member());
create policy "recurring: admins borran" on public.recurring for delete using (public.is_admin());
-- Registro de actividad: quien hizo que y cuando. Solo dueno y admin lo leen; nadie lo puede editar ni borrar desde la app.
create table if not exists public.audit ( id bigserial primary key, at timestamptz not null default now(), user_id uuid, email text, tbl text not null, row_id text, action text not null, old jsonb, new jsonb );
create index if not exists audit_at_idx on public.audit (at desc);
alter table public.audit enable row level security;
revoke all on public.audit from anon, authenticated;
grant select on public.audit to authenticated;
drop policy if exists "audit: admins leen" on public.audit;
create policy "audit: admins leen" on public.audit for select using (public.is_admin());
create or replace function public.log_change() returns trigger language plpgsql security definer set search_path = public as $$ declare v_old jsonb; v_new jsonb; begin if TG_OP <> 'INSERT' then v_old := to_jsonb(old) - 'image'; end if; if TG_OP <> 'DELETE' then v_new := to_jsonb(new) - 'image'; end if; if TG_OP = 'UPDATE' and (v_old - 'updated_at') = (v_new - 'updated_at') then return new; end if; insert into public.audit (user_id, email, tbl, row_id, action, old, new) values (auth.uid(), (select email from auth.users where id = auth.uid()), TG_TABLE_NAME, coalesce(v_new ->> 'id', v_old ->> 'id', v_new ->> 'user_id', v_old ->> 'user_id'), lower(TG_OP), v_old, v_new); return coalesce(new, old); end; $$;
revoke all on function public.log_change() from public;
drop trigger if exists audit_orders on public.orders;
create trigger audit_orders after insert or update or delete on public.orders for each row execute function public.log_change();
drop trigger if exists audit_clients on public.clients;
create trigger audit_clients after insert or update or delete on public.clients for each row execute function public.log_change();
drop trigger if exists audit_offerings on public.offerings;
create trigger audit_offerings after insert or update or delete on public.offerings for each row execute function public.log_change();
drop trigger if exists audit_expenses on public.expenses;
create trigger audit_expenses after insert or update or delete on public.expenses for each row execute function public.log_change();
drop trigger if exists audit_invoices on public.invoices;
create trigger audit_invoices after insert or update or delete on public.invoices for each row execute function public.log_change();
drop trigger if exists audit_recurring on public.recurring;
create trigger audit_recurring after insert or update or delete on public.recurring for each row execute function public.log_change();
drop trigger if exists audit_members on public.members;
create trigger audit_members after insert or update or delete on public.members for each row execute function public.log_change();
drop trigger if exists audit_projects on public.projects;
create trigger audit_projects after insert or update or delete on public.projects for each row execute function public.log_change();
-- Pedidos desde la web: fecha hasta 60 dias, maximo 30 por hora en total y 5 por dia por telefono.
create or replace function public.place_web_order( p_client text, p_phone text, p_date date, p_lines jsonb, p_note text default null ) returns uuid language plpgsql security definer set search_path = public as $$ declare v_items jsonb := '[]'::jsonb; v_line jsonb; v_off public.offerings; v_qty integer; v_id uuid; begin if coalesce(trim(p_client), '') = '' then raise exception 'falta el nombre'; end if; if p_date < current_date then raise exception 'fecha en el pasado'; end if; if p_date > current_date + 60 then raise exception 'fecha muy lejana'; end if; if (select count(*) from public.orders where source = 'web' and created_at > now() - interval '1 hour') >= 30 then raise exception 'Muchos pedidos en este momento, intenta en un rato'; end if; if coalesce(trim(p_phone), '') <> '' and (select count(*) from public.orders where source = 'web' and phone = left(p_phone, 40) and created_at > now() - interval '1 day') >= 5 then raise exception 'Ya recibimos varios pedidos de este teléfono hoy; escríbenos'; end if; if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then raise exception 'pedido vacio'; end if; for v_line in select * from jsonb_array_elements(p_lines) loop v_qty := (v_line ->> 'qty')::integer; if v_qty is null or v_qty < 1 or v_qty > 50 then raise exception 'cantidad invalida'; end if; select * into v_off from public.offerings where code = upper(v_line ->> 'code') and active and public; if not found then raise exception 'codigo no disponible: %', v_line ->> 'code'; end if; v_items := v_items || jsonb_build_object( 'offeringId', v_off.id, 'code', v_off.code, 'name', v_off.name, 'qty', v_qty, 'unitPrice', case when v_off.promo_price is not null and v_off.promo_until >= p_date then v_off.promo_price else v_off.price end); end loop; insert into public.orders (client, phone, date, items, note, source) values (left(trim(p_client), 120), left(p_phone, 40), p_date, v_items, left(p_note, 500), 'web') returning id into v_id; return v_id; end; $$;
