-- Divine Circle: seguridad (equipo y bloqueo del hub anterior). Una sentencia por linea. Pegar todo y Run, despues de setup.sql.
create or replace function public.team() returns table (user_id uuid, email text, role text, created_at timestamptz) language sql stable security definer set search_path = public as $$ select m.user_id, coalesce(u.email, m.name), m.role, m.created_at from public.members m left join auth.users u on u.id = m.user_id where public.is_member() order by m.created_at; $$;
create or replace function public.set_member(p_email text, p_role text) returns text language plpgsql security definer set search_path = public as $$ declare v_id uuid; begin if not public.is_admin() then raise exception 'solo dueno o admin'; end if; if p_role not in ('owner', 'admin', 'staff') then raise exception 'rol invalido'; end if; if p_role = 'owner' and not exists (select 1 from public.members where user_id = auth.uid() and role = 'owner') then raise exception 'solo el dueno puede nombrar otro dueno'; end if; select id into v_id from auth.users where lower(email) = lower(trim(p_email)); if v_id is null then return 'sin cuenta'; end if; if exists (select 1 from public.members where user_id = v_id and role = 'owner') and p_role <> 'owner' and (select count(*) from public.members where role = 'owner') = 1 then raise exception 'debe quedar al menos un dueno'; end if; insert into public.members (user_id, name, role) values (v_id, lower(trim(p_email)), p_role) on conflict (user_id) do update set role = excluded.role; return 'ok'; end; $$;
create or replace function public.remove_member(p_user uuid) returns text language plpgsql security definer set search_path = public as $$ begin if not public.is_admin() then raise exception 'solo dueno o admin'; end if; if exists (select 1 from public.members where user_id = p_user and role = 'owner') then if not exists (select 1 from public.members where user_id = auth.uid() and role = 'owner') then raise exception 'solo el dueno puede quitar a un dueno'; end if; if (select count(*) from public.members where role = 'owner') = 1 then raise exception 'debe quedar al menos un dueno'; end if; end if; delete from public.members where user_id = p_user; return 'ok'; end; $$;
revoke all on function public.team() from public;
revoke all on function public.set_member(text, text) from public;
revoke all on function public.remove_member(uuid) from public;
grant execute on function public.team() to authenticated;
grant execute on function public.set_member(text, text) to authenticated;
grant execute on function public.remove_member(uuid) to authenticated;
drop policy if exists "members: admins gestionan" on public.members;
revoke insert, update, delete on public.members from anon, authenticated;
do $$ begin if to_regclass('public.divine_circle_data') is not null then execute 'alter table public.divine_circle_data enable row level security'; execute 'revoke all on public.divine_circle_data from anon'; end if; if to_regclass('public.divine_circle_backups') is not null then execute 'alter table public.divine_circle_backups enable row level security'; execute 'revoke all on public.divine_circle_backups from anon'; end if; end $$;
revoke all on function public.place_web_order(text, text, date, jsonb, text) from public;
grant execute on function public.place_web_order(text, text, date, jsonb, text) to anon, authenticated;
